# Python para Análise de Dados - Numpy   

<p> Iremos aprender a trabalhar coma biblioteca Numpy.


# Acessando Dimensões no Array

In [16]:
# Importando o Numpy
import numpy as np

In [17]:
# Gera um array aleatório de 10 linhas e 2 colunas
# formato linha,coluna
my_array = np.random.random([10,2])

In [18]:
my_array

array([[ 0.60651997,  0.46694674],
       [ 0.89973659,  0.79650252],
       [ 0.03080252,  0.60592395],
       [ 0.48612475,  0.42404389],
       [ 0.0919636 ,  0.47582731],
       [ 0.74807751,  0.04497495],
       [ 0.41616975,  0.23221181],
       [ 0.63072672,  0.65586839],
       [ 0.64283871,  0.07817103],
       [ 0.57021475,  0.82074198]])

In [19]:
# Imprimindo o primeiro elemento (1 linha)
my_array[0]

array([ 0.60651997,  0.46694674])

In [20]:
# Imprimindo o primeiro elemento da coluna 0 (1 coluna)
my_array[0][0]

0.60651996578382938

In [21]:
# Primeiro elemento da coluna 1
my_array[0][1]

0.46694673787644625

In [22]:
# Segundo elemento da coluna 1
my_array[1][1]

0.79650252037982416

In [23]:
# Segundo elemento da coluna escrito com virgula.
# O primeiro valor especifica a linha e o segundo valor especifica a coluna.
my_array[1,1]

0.79650252037982416

In [24]:
# Imprimindo até 3 valores da coluna 1
my_array[:3,1]

array([ 0.46694674,  0.79650252,  0.60592395])

In [25]:
# Imprime todas as linhas da coluna 2 * 10
my_array[:,1] * 10

array([ 4.66946738,  7.9650252 ,  6.05923945,  4.24043892,  4.75827314,
        0.44974946,  2.32211812,  6.55868387,  0.78171032,  8.20741982])

In [26]:
# Comparação retorna indices
my_array > 0.50

array([[ True, False],
       [ True,  True],
       [False,  True],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [ True,  True],
       [ True, False],
       [ True,  True]], dtype=bool)

In [27]:
# Acessando valores por índices
my_array[my_array > 0.50]

array([ 0.60651997,  0.89973659,  0.79650252,  0.60592395,  0.74807751,
        0.63072672,  0.65586839,  0.64283871,  0.57021475,  0.82074198])

# Carregar Arrays NumPy a partir de arquivos de Texto

In [ ]:
import numpy as np

In [28]:
# Lendo um arquivo do tipo .txt
dataset = np.loadtxt('dataset_array.txt', delimiter=',')

In [29]:
dataset.shape

(6,)

In [30]:
dataset

array([ 1.,  2.,  3.,  4.,  5.,  6.])

In [31]:
# carregando um arquivo dividido em 3 arrays
a, b, c = np.loadtxt('dataset_valores.txt', skiprows=1, unpack=True )

In [32]:
# Array a
a

array([ 0.4839,  0.1292,  0.1781,  0.7676,  0.5993])

In [33]:
# Array B
b

array([ 0.4536,  0.6875,  0.3049,  0.5801,  0.4357])

In [34]:
# Array C
c

array([ 0.3561,  0.6565,  0.8928,  0.2038,  0.741 ])

In [35]:
# Carrega o arquivo ignorando as 2 primeiras linhas e preenchendo os valores vazio por 0
# Obs: os valores string também são convertidos!!

dataset = np.genfromtxt('dataset_valores_vazio.txt', skip_header=2, filling_values=0)

In [36]:
# Imprimindo o dataset
dataset

array([[ 0.4839,  0.4536,  0.3561],
       [ 0.1292,  0.6875,  0.    ],
       [ 0.1781,  0.3049,  0.8928],
       [ 0.    ,  0.5801,  0.2038],
       [ 0.5993,  0.4357,  0.741 ]])