# Python para Análise de Dados - Numpy   

<p> Iremos aprender a trabalhar coma biblioteca Numpy.


In [ ]:
# Importando a biblioteca numpy
import numpy as np

In [ ]:
# Criando um array de 1 dimensão
one_dim = np.array([1,2,3,4])

In [ ]:
type(one_dim)

In [ ]:
# Imprimindo um array.
one_dim.ndim

In [ ]:
# Criando um array de 2 dimensões.
two_dim = np.array([(1,2,3), (4,5,6)])

In [ ]:
# Imprimindo o array
two_dim.ndim

In [ ]:
# Cria um array de números aleatórios.
# Um array de 5 linhas e duas dimensões.
np.random.random((5,2))

In [ ]:
# Cria um array com valores esparsos iniciando com o valor 10, menor que 50 e incrementando de 5 em 5.
np.arange(10,50,5)

In [ ]:
# cria um array linear de 0 a 2 de no máximo 9 elementos.
np.linspace(0,2,9)

In [ ]:
# Cria um array de valores zero.
# Cria um array com 3 linhas e 4 dimensões.
np.zeros((3,4))

# Numpy Arrays Vs Listas

- Arrays Numpy permitem fazermos operações em **arrays inteiros** de forma rápida.
- Listas não permitem operações em todos os elementos da lista.
- Para operações em todos os elementos é preciso interar sobre toda a lista.
- Listas em Python armazenam diferentes tipos de objetos
- Arrays Numpy considera todos os elementos de tipos distintos como strings


In [ ]:
# Criando uma lista em Python.
lista = [1,2,3]

In [ ]:
lista

In [ ]:
# Multiplicar valores da lista por 2.
lista * 2

In [ ]:
# Transforme a variável lista em um array Numpy
lista = np.array(lista)

In [ ]:
# Imprimindo o tipo do objeto.
type(lista)

In [ ]:
# Multiplicando cada elemento por 2.
lista * 2

In [ ]:
# Calcular IMC de pessoas.
pesos = [67,81,120,90]
altura = [1.68,1.70,1.75,1.85]

In [ ]:
# Faz o calculo usando as listas
pesos / altura ** 2

In [ ]:
# Transforme isso em arrays numpy
pesos = np.array(pesos)
altura = np.array(altura)

In [ ]:
# Imprime o calculo de cada valor
pesos / altura **2

In [ ]:
# Arrays Numpy armazena elementos como strins quando estes não são inteiros ou float
a = np.array([1,3,'Casa',True])

In [ ]:
a

In [ ]:
a * 2 

# Métodos e Atributos Úteis

In [ ]:
# Métodos disponíveis (digite o . pressione tab).
two_dim.

In [115]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
# Retorna a forma do array no formato linhas e colunas.
two_dim.shape

(2, 3)

In [117]:
# Retorna a quantidade de dimensões.
two_dim.ndim

2

In [118]:
# Imprimindo o valor máximo do array.
two_dim.max()

6

In [119]:
# Imprimindo o valor mínimo.
two_dim.min()

1

In [120]:
# Imprimindo o valor médio.
two_dim.mean()

3.5

In [121]:
# Imprimindo o desvio padrão.
two_dim.std()

1.707825127659933

In [122]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [123]:
two_dim.dtype

dtype('int64')

In [124]:
two_dim.size

6

In [126]:
# mostra a quantidade
two_dim.itemsize

8

In [127]:
# Somando todos os elementos do array.
two_dim.sum()

21

#  Transformando Arrays

In [128]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [129]:
# Gera a Transposta da Matriz (Linha -> coluna)
two_dim.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [130]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [131]:
# Transforma em uma matriz de uma linha.
# È muito comum em bibliotecas como scikit-learn e Keras
two_dim.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [132]:
tree = np.random.random((5,3))

In [133]:
tree.shape

(5, 3)

In [134]:
tree

array([[ 0.91196854,  0.68623392,  0.17075595],
       [ 0.39525594,  0.92923579,  0.696779  ],
       [ 0.45495045,  0.37674542,  0.34936873],
       [ 0.49264174,  0.4806529 ,  0.03501355],
       [ 0.74656606,  0.4963808 ,  0.24223196]])

In [135]:
# Transforma em uma matriz com 3 linhas e 5 colunas
tree.reshape(3,5)

array([[ 0.91196854,  0.68623392,  0.17075595,  0.39525594,  0.92923579],
       [ 0.696779  ,  0.45495045,  0.37674542,  0.34936873,  0.49264174],
       [ 0.4806529 ,  0.03501355,  0.74656606,  0.4963808 ,  0.24223196]])

In [137]:
tree.reshape(-1)

array([ 0.91196854,  0.68623392,  0.17075595,  0.39525594,  0.92923579,
        0.696779  ,  0.45495045,  0.37674542,  0.34936873,  0.49264174,
        0.4806529 ,  0.03501355,  0.74656606,  0.4963808 ,  0.24223196])

In [139]:
t=tree.reshape(1,15)
t

array([[ 0.91196854,  0.68623392,  0.17075595,  0.39525594,  0.92923579,
         0.696779  ,  0.45495045,  0.37674542,  0.34936873,  0.49264174,
         0.4806529 ,  0.03501355,  0.74656606,  0.4963808 ,  0.24223196]])

In [140]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [141]:
# Adicionando elementos a um array.
two_dim = np.insert(two_dim,0,10)

In [142]:
# Transforma em um array de uma linha.
two_dim

array([10,  1,  2,  3,  4,  5,  6])

In [143]:
# Apagando o elemento da primeira posição do array.
two_dim = np.delete(two_dim,[0])

In [144]:
two_dim

array([1, 2, 3, 4, 5, 6])

In [145]:
# Gerando um arquivo .txt a partir de um array
np.savetxt("dataset_array.txt",two_dim, delimiter=',')